# shellcheck shell=sh

#
# Colors library (generated by: color)

# <html><h2>Bold</h2>
# <p><strong><code>$Bold</code></strong> Color Bold.</p>
# </html>
export Bold="\033[1m"

# <html><h2>BoldItalic</h2>
# <p><strong><code>$BoldItalic</code></strong> Color BoldItalic.</p>
# </html>
export BoldItalic="\033[3m\033[1m"

# <html><h2>Dim</h2>
# <p><strong><code>$Dim</code></strong> Color Dim.</p>
# </html>
export Dim="\033[2m"

# <html><h2>Invert</h2>
# <p><strong><code>$Invert</code></strong> Color Invert.</p>
# </html>
export Invert="\033[7m"

# <html><h2>Italic</h2>
# <p><strong><code>$Italic</code></strong> Color Italic.</p>
# </html>
export Italic="\033[3m"

# <html><h2>Normal</h2>
# <p><strong><code>$Normal</code></strong> Color Normal.</p>
# </html>
export Normal="\033[0m"

# <html><h2>Strike</h2>
# <p><strong><code>$Strike</code></strong> Color Strike.</p>
# </html>
export Strike="\033[9m"

# <html><h2>Under</h2>
# <p><strong><code>$Under</code></strong> Color Under.</p>
# </html>
export Under="\033[4m"

# <html><h2>Black</h2>
# <p><strong><code>$Black</code></strong> Color Black.</p>
# </html>
export Black="\033[1;30m"

# <html><h2>BlackBg</h2>
# <p><strong><code>$BlackBg</code></strong> Color BlackBg.</p>
# </html>
export BlackBg="\033[1;40m"

# <html><h2>BlackBoldItalic</h2>
# <p><strong><code>$BlackBoldItalic</code></strong> Color BlackBoldItalic.</p>
# </html>
export BlackBoldItalic="\033[3m\033[1;30m"

# <html><h2>BlackBoldItalicBg</h2>
# <p><strong><code>$BlackBoldItalicBg</code></strong> Color BlackBoldItalicBg.</p>
# </html>
export BlackBoldItalicBg="\033[3m\033[1;40m"

# <html><h2>BlackDim</h2>
# <p><strong><code>$BlackDim</code></strong> Color BlackDim.</p>
# </html>
export BlackDim="\033[2;30m"

# <html><h2>BlackDimBg</h2>
# <p><strong><code>$BlackDimBg</code></strong> Color BlackDimBg.</p>
# </html>
export BlackDimBg="\033[2;40m"

# <html><h2>BlackInvert</h2>
# <p><strong><code>$BlackInvert</code></strong> Color BlackInvert.</p>
# </html>
export BlackInvert="\033[7;30m"

# <html><h2>BlackInvertBg</h2>
# <p><strong><code>$BlackInvertBg</code></strong> Color BlackInvertBg.</p>
# </html>
export BlackInvertBg="\033[7;40m"

# <html><h2>BlackItalic</h2>
# <p><strong><code>$BlackItalic</code></strong> Color BlackItalic.</p>
# </html>
export BlackItalic="\033[3;30m"

# <html><h2>BlackItalicBg</h2>
# <p><strong><code>$BlackItalicBg</code></strong> Color BlackItalicBg.</p>
# </html>
export BlackItalicBg="\033[3;40m"

# <html><h2>BlackNormal</h2>
# <p><strong><code>$BlackNormal</code></strong> Color BlackNormal.</p>
# </html>
export BlackNormal="\033[0;30m"

# <html><h2>BlackNormalBg</h2>
# <p><strong><code>$BlackNormalBg</code></strong> Color BlackNormalBg.</p>
# </html>
export BlackNormalBg="\033[0;40m"

# <html><h2>BlackStrike</h2>
# <p><strong><code>$BlackStrike</code></strong> Color BlackStrike.</p>
# </html>
export BlackStrike="\033[9;30m"

# <html><h2>BlackStrikeBg</h2>
# <p><strong><code>$BlackStrikeBg</code></strong> Color BlackStrikeBg.</p>
# </html>
export BlackStrikeBg="\033[9;40m"

# <html><h2>BlackUnder</h2>
# <p><strong><code>$BlackUnder</code></strong> Color BlackUnder.</p>
# </html>
export BlackUnder="\033[4;30m"

# <html><h2>BlackUnderBg</h2>
# <p><strong><code>$BlackUnderBg</code></strong> Color BlackUnderBg.</p>
# </html>
export BlackUnderBg="\033[4;40m"

# <html><h2>Blue</h2>
# <p><strong><code>$Blue</code></strong> Color Blue.</p>
# </html>
export Blue="\033[1;34m"

# <html><h2>BlueBg</h2>
# <p><strong><code>$BlueBg</code></strong> Color BlueBg.</p>
# </html>
export BlueBg="\033[1;44m"

# <html><h2>BlueBoldItalic</h2>
# <p><strong><code>$BlueBoldItalic</code></strong> Color BlueBoldItalic.</p>
# </html>
export BlueBoldItalic="\033[3m\033[1;34m"

# <html><h2>BlueBoldItalicBg</h2>
# <p><strong><code>$BlueBoldItalicBg</code></strong> Color BlueBoldItalicBg.</p>
# </html>
export BlueBoldItalicBg="\033[3m\033[1;44m"

# <html><h2>BlueDim</h2>
# <p><strong><code>$BlueDim</code></strong> Color BlueDim.</p>
# </html>
export BlueDim="\033[2;34m"

# <html><h2>BlueDimBg</h2>
# <p><strong><code>$BlueDimBg</code></strong> Color BlueDimBg.</p>
# </html>
export BlueDimBg="\033[2;44m"

# <html><h2>BlueInvert</h2>
# <p><strong><code>$BlueInvert</code></strong> Color BlueInvert.</p>
# </html>
export BlueInvert="\033[7;34m"

# <html><h2>BlueInvertBg</h2>
# <p><strong><code>$BlueInvertBg</code></strong> Color BlueInvertBg.</p>
# </html>
export BlueInvertBg="\033[7;44m"

# <html><h2>BlueItalic</h2>
# <p><strong><code>$BlueItalic</code></strong> Color BlueItalic.</p>
# </html>
export BlueItalic="\033[3;34m"

# <html><h2>BlueItalicBg</h2>
# <p><strong><code>$BlueItalicBg</code></strong> Color BlueItalicBg.</p>
# </html>
export BlueItalicBg="\033[3;44m"

# <html><h2>BlueNormal</h2>
# <p><strong><code>$BlueNormal</code></strong> Color BlueNormal.</p>
# </html>
export BlueNormal="\033[0;34m"

# <html><h2>BlueNormalBg</h2>
# <p><strong><code>$BlueNormalBg</code></strong> Color BlueNormalBg.</p>
# </html>
export BlueNormalBg="\033[0;44m"

# <html><h2>BlueStrike</h2>
# <p><strong><code>$BlueStrike</code></strong> Color BlueStrike.</p>
# </html>
export BlueStrike="\033[9;34m"

# <html><h2>BlueStrikeBg</h2>
# <p><strong><code>$BlueStrikeBg</code></strong> Color BlueStrikeBg.</p>
# </html>
export BlueStrikeBg="\033[9;44m"

# <html><h2>BlueUnder</h2>
# <p><strong><code>$BlueUnder</code></strong> Color BlueUnder.</p>
# </html>
export BlueUnder="\033[4;34m"

# <html><h2>BlueUnderBg</h2>
# <p><strong><code>$BlueUnderBg</code></strong> Color BlueUnderBg.</p>
# </html>
export BlueUnderBg="\033[4;44m"

# <html><h2>Cyan</h2>
# <p><strong><code>$Cyan</code></strong> Color Cyan.</p>
# </html>
export Cyan="\033[1;36m"

# <html><h2>CyanBg</h2>
# <p><strong><code>$CyanBg</code></strong> Color CyanBg.</p>
# </html>
export CyanBg="\033[1;46m"

# <html><h2>CyanBoldItalic</h2>
# <p><strong><code>$CyanBoldItalic</code></strong> Color CyanBoldItalic.</p>
# </html>
export CyanBoldItalic="\033[3m\033[1;36m"

# <html><h2>CyanBoldItalicBg</h2>
# <p><strong><code>$CyanBoldItalicBg</code></strong> Color CyanBoldItalicBg.</p>
# </html>
export CyanBoldItalicBg="\033[3m\033[1;46m"

# <html><h2>CyanDim</h2>
# <p><strong><code>$CyanDim</code></strong> Color CyanDim.</p>
# </html>
export CyanDim="\033[2;36m"

# <html><h2>CyanDimBg</h2>
# <p><strong><code>$CyanDimBg</code></strong> Color CyanDimBg.</p>
# </html>
export CyanDimBg="\033[2;46m"

# <html><h2>CyanInvert</h2>
# <p><strong><code>$CyanInvert</code></strong> Color CyanInvert.</p>
# </html>
export CyanInvert="\033[7;36m"

# <html><h2>CyanInvertBg</h2>
# <p><strong><code>$CyanInvertBg</code></strong> Color CyanInvertBg.</p>
# </html>
export CyanInvertBg="\033[7;46m"

# <html><h2>CyanItalic</h2>
# <p><strong><code>$CyanItalic</code></strong> Color CyanItalic.</p>
# </html>
export CyanItalic="\033[3;36m"

# <html><h2>CyanItalicBg</h2>
# <p><strong><code>$CyanItalicBg</code></strong> Color CyanItalicBg.</p>
# </html>
export CyanItalicBg="\033[3;46m"

# <html><h2>CyanNormal</h2>
# <p><strong><code>$CyanNormal</code></strong> Color CyanNormal.</p>
# </html>
export CyanNormal="\033[0;36m"

# <html><h2>CyanNormalBg</h2>
# <p><strong><code>$CyanNormalBg</code></strong> Color CyanNormalBg.</p>
# </html>
export CyanNormalBg="\033[0;46m"

# <html><h2>CyanStrike</h2>
# <p><strong><code>$CyanStrike</code></strong> Color CyanStrike.</p>
# </html>
export CyanStrike="\033[9;36m"

# <html><h2>CyanStrikeBg</h2>
# <p><strong><code>$CyanStrikeBg</code></strong> Color CyanStrikeBg.</p>
# </html>
export CyanStrikeBg="\033[9;46m"

# <html><h2>CyanUnder</h2>
# <p><strong><code>$CyanUnder</code></strong> Color CyanUnder.</p>
# </html>
export CyanUnder="\033[4;36m"

# <html><h2>CyanUnderBg</h2>
# <p><strong><code>$CyanUnderBg</code></strong> Color CyanUnderBg.</p>
# </html>
export CyanUnderBg="\033[4;46m"

# <html><h2>Green</h2>
# <p><strong><code>$Green</code></strong> Color Green.</p>
# </html>
export Green="\033[1;32m"

# <html><h2>GreenBg</h2>
# <p><strong><code>$GreenBg</code></strong> Color GreenBg.</p>
# </html>
export GreenBg="\033[1;42m"

# <html><h2>GreenBoldItalic</h2>
# <p><strong><code>$GreenBoldItalic</code></strong> Color GreenBoldItalic.</p>
# </html>
export GreenBoldItalic="\033[3m\033[1;32m"

# <html><h2>GreenBoldItalicBg</h2>
# <p><strong><code>$GreenBoldItalicBg</code></strong> Color GreenBoldItalicBg.</p>
# </html>
export GreenBoldItalicBg="\033[3m\033[1;42m"

# <html><h2>GreenDim</h2>
# <p><strong><code>$GreenDim</code></strong> Color GreenDim.</p>
# </html>
export GreenDim="\033[2;32m"

# <html><h2>GreenDimBg</h2>
# <p><strong><code>$GreenDimBg</code></strong> Color GreenDimBg.</p>
# </html>
export GreenDimBg="\033[2;42m"

# <html><h2>GreenInvert</h2>
# <p><strong><code>$GreenInvert</code></strong> Color GreenInvert.</p>
# </html>
export GreenInvert="\033[7;32m"

# <html><h2>GreenInvertBg</h2>
# <p><strong><code>$GreenInvertBg</code></strong> Color GreenInvertBg.</p>
# </html>
export GreenInvertBg="\033[7;42m"

# <html><h2>GreenItalic</h2>
# <p><strong><code>$GreenItalic</code></strong> Color GreenItalic.</p>
# </html>
export GreenItalic="\033[3;32m"

# <html><h2>GreenItalicBg</h2>
# <p><strong><code>$GreenItalicBg</code></strong> Color GreenItalicBg.</p>
# </html>
export GreenItalicBg="\033[3;42m"

# <html><h2>GreenNormal</h2>
# <p><strong><code>$GreenNormal</code></strong> Color GreenNormal.</p>
# </html>
export GreenNormal="\033[0;32m"

# <html><h2>GreenNormalBg</h2>
# <p><strong><code>$GreenNormalBg</code></strong> Color GreenNormalBg.</p>
# </html>
export GreenNormalBg="\033[0;42m"

# <html><h2>GreenStrike</h2>
# <p><strong><code>$GreenStrike</code></strong> Color GreenStrike.</p>
# </html>
export GreenStrike="\033[9;32m"

# <html><h2>GreenStrikeBg</h2>
# <p><strong><code>$GreenStrikeBg</code></strong> Color GreenStrikeBg.</p>
# </html>
export GreenStrikeBg="\033[9;42m"

# <html><h2>GreenUnder</h2>
# <p><strong><code>$GreenUnder</code></strong> Color GreenUnder.</p>
# </html>
export GreenUnder="\033[4;32m"

# <html><h2>GreenUnderBg</h2>
# <p><strong><code>$GreenUnderBg</code></strong> Color GreenUnderBg.</p>
# </html>
export GreenUnderBg="\033[4;42m"

# <html><h2>Grey</h2>
# <p><strong><code>$Grey</code></strong> Color Grey.</p>
# </html>
export Grey="\033[1;37m"

# <html><h2>GreyBg</h2>
# <p><strong><code>$GreyBg</code></strong> Color GreyBg.</p>
# </html>
export GreyBg="\033[1;47m"

# <html><h2>GreyBoldItalic</h2>
# <p><strong><code>$GreyBoldItalic</code></strong> Color GreyBoldItalic.</p>
# </html>
export GreyBoldItalic="\033[3m\033[1;37m"

# <html><h2>GreyBoldItalicBg</h2>
# <p><strong><code>$GreyBoldItalicBg</code></strong> Color GreyBoldItalicBg.</p>
# </html>
export GreyBoldItalicBg="\033[3m\033[1;47m"

# <html><h2>GreyDim</h2>
# <p><strong><code>$GreyDim</code></strong> Color GreyDim.</p>
# </html>
export GreyDim="\033[2;37m"

# <html><h2>GreyDimBg</h2>
# <p><strong><code>$GreyDimBg</code></strong> Color GreyDimBg.</p>
# </html>
export GreyDimBg="\033[2;47m"

# <html><h2>GreyInvert</h2>
# <p><strong><code>$GreyInvert</code></strong> Color GreyInvert.</p>
# </html>
export GreyInvert="\033[7;37m"

# <html><h2>GreyInvertBg</h2>
# <p><strong><code>$GreyInvertBg</code></strong> Color GreyInvertBg.</p>
# </html>
export GreyInvertBg="\033[7;47m"

# <html><h2>GreyItalic</h2>
# <p><strong><code>$GreyItalic</code></strong> Color GreyItalic.</p>
# </html>
export GreyItalic="\033[3;37m"

# <html><h2>GreyItalicBg</h2>
# <p><strong><code>$GreyItalicBg</code></strong> Color GreyItalicBg.</p>
# </html>
export GreyItalicBg="\033[3;47m"

# <html><h2>GreyNormal</h2>
# <p><strong><code>$GreyNormal</code></strong> Color GreyNormal.</p>
# </html>
export GreyNormal="\033[0;37m"

# <html><h2>GreyNormalBg</h2>
# <p><strong><code>$GreyNormalBg</code></strong> Color GreyNormalBg.</p>
# </html>
export GreyNormalBg="\033[0;47m"

# <html><h2>GreyStrike</h2>
# <p><strong><code>$GreyStrike</code></strong> Color GreyStrike.</p>
# </html>
export GreyStrike="\033[9;37m"

# <html><h2>GreyStrikeBg</h2>
# <p><strong><code>$GreyStrikeBg</code></strong> Color GreyStrikeBg.</p>
# </html>
export GreyStrikeBg="\033[9;47m"

# <html><h2>GreyUnder</h2>
# <p><strong><code>$GreyUnder</code></strong> Color GreyUnder.</p>
# </html>
export GreyUnder="\033[4;37m"

# <html><h2>GreyUnderBg</h2>
# <p><strong><code>$GreyUnderBg</code></strong> Color GreyUnderBg.</p>
# </html>
export GreyUnderBg="\033[4;47m"

# <html><h2>Magenta</h2>
# <p><strong><code>$Magenta</code></strong> Color Magenta.</p>
# </html>
export Magenta="\033[1;35m"

# <html><h2>MagentaBg</h2>
# <p><strong><code>$MagentaBg</code></strong> Color MagentaBg.</p>
# </html>
export MagentaBg="\033[1;45m"

# <html><h2>MagentaBoldItalic</h2>
# <p><strong><code>$MagentaBoldItalic</code></strong> Color MagentaBoldItalic.</p>
# </html>
export MagentaBoldItalic="\033[3m\033[1;35m"

# <html><h2>MagentaBoldItalicBg</h2>
# <p><strong><code>$MagentaBoldItalicBg</code></strong> Color MagentaBoldItalicBg.</p>
# </html>
export MagentaBoldItalicBg="\033[3m\033[1;45m"

# <html><h2>MagentaDim</h2>
# <p><strong><code>$MagentaDim</code></strong> Color MagentaDim.</p>
# </html>
export MagentaDim="\033[2;35m"

# <html><h2>MagentaDimBg</h2>
# <p><strong><code>$MagentaDimBg</code></strong> Color MagentaDimBg.</p>
# </html>
export MagentaDimBg="\033[2;45m"

# <html><h2>MagentaInvert</h2>
# <p><strong><code>$MagentaInvert</code></strong> Color MagentaInvert.</p>
# </html>
export MagentaInvert="\033[7;35m"

# <html><h2>MagentaInvertBg</h2>
# <p><strong><code>$MagentaInvertBg</code></strong> Color MagentaInvertBg.</p>
# </html>
export MagentaInvertBg="\033[7;45m"

# <html><h2>MagentaItalic</h2>
# <p><strong><code>$MagentaItalic</code></strong> Color MagentaItalic.</p>
# </html>
export MagentaItalic="\033[3;35m"

# <html><h2>MagentaItalicBg</h2>
# <p><strong><code>$MagentaItalicBg</code></strong> Color MagentaItalicBg.</p>
# </html>
export MagentaItalicBg="\033[3;45m"

# <html><h2>MagentaNormal</h2>
# <p><strong><code>$MagentaNormal</code></strong> Color MagentaNormal.</p>
# </html>
export MagentaNormal="\033[0;35m"

# <html><h2>MagentaNormalBg</h2>
# <p><strong><code>$MagentaNormalBg</code></strong> Color MagentaNormalBg.</p>
# </html>
export MagentaNormalBg="\033[0;45m"

# <html><h2>MagentaStrike</h2>
# <p><strong><code>$MagentaStrike</code></strong> Color MagentaStrike.</p>
# </html>
export MagentaStrike="\033[9;35m"

# <html><h2>MagentaStrikeBg</h2>
# <p><strong><code>$MagentaStrikeBg</code></strong> Color MagentaStrikeBg.</p>
# </html>
export MagentaStrikeBg="\033[9;45m"

# <html><h2>MagentaUnder</h2>
# <p><strong><code>$MagentaUnder</code></strong> Color MagentaUnder.</p>
# </html>
export MagentaUnder="\033[4;35m"

# <html><h2>MagentaUnderBg</h2>
# <p><strong><code>$MagentaUnderBg</code></strong> Color MagentaUnderBg.</p>
# </html>
export MagentaUnderBg="\033[4;45m"

# <html><h2>Red</h2>
# <p><strong><code>$Red</code></strong> Color Red.</p>
# </html>
export Red="\033[1;31m"

# <html><h2>RedBg</h2>
# <p><strong><code>$RedBg</code></strong> Color RedBg.</p>
# </html>
export RedBg="\033[1;41m"

# <html><h2>RedBoldItalic</h2>
# <p><strong><code>$RedBoldItalic</code></strong> Color RedBoldItalic.</p>
# </html>
export RedBoldItalic="\033[3m\033[1;31m"

# <html><h2>RedBoldItalicBg</h2>
# <p><strong><code>$RedBoldItalicBg</code></strong> Color RedBoldItalicBg.</p>
# </html>
export RedBoldItalicBg="\033[3m\033[1;41m"

# <html><h2>RedDim</h2>
# <p><strong><code>$RedDim</code></strong> Color RedDim.</p>
# </html>
export RedDim="\033[2;31m"

# <html><h2>RedDimBg</h2>
# <p><strong><code>$RedDimBg</code></strong> Color RedDimBg.</p>
# </html>
export RedDimBg="\033[2;41m"

# <html><h2>RedInvert</h2>
# <p><strong><code>$RedInvert</code></strong> Color RedInvert.</p>
# </html>
export RedInvert="\033[7;31m"

# <html><h2>RedInvertBg</h2>
# <p><strong><code>$RedInvertBg</code></strong> Color RedInvertBg.</p>
# </html>
export RedInvertBg="\033[7;41m"

# <html><h2>RedItalic</h2>
# <p><strong><code>$RedItalic</code></strong> Color RedItalic.</p>
# </html>
export RedItalic="\033[3;31m"

# <html><h2>RedItalicBg</h2>
# <p><strong><code>$RedItalicBg</code></strong> Color RedItalicBg.</p>
# </html>
export RedItalicBg="\033[3;41m"

# <html><h2>RedNormal</h2>
# <p><strong><code>$RedNormal</code></strong> Color RedNormal.</p>
# </html>
export RedNormal="\033[0;31m"

# <html><h2>RedNormalBg</h2>
# <p><strong><code>$RedNormalBg</code></strong> Color RedNormalBg.</p>
# </html>
export RedNormalBg="\033[0;41m"

# <html><h2>RedStrike</h2>
# <p><strong><code>$RedStrike</code></strong> Color RedStrike.</p>
# </html>
export RedStrike="\033[9;31m"

# <html><h2>RedStrikeBg</h2>
# <p><strong><code>$RedStrikeBg</code></strong> Color RedStrikeBg.</p>
# </html>
export RedStrikeBg="\033[9;41m"

# <html><h2>RedUnder</h2>
# <p><strong><code>$RedUnder</code></strong> Color RedUnder.</p>
# </html>
export RedUnder="\033[4;31m"

# <html><h2>RedUnderBg</h2>
# <p><strong><code>$RedUnderBg</code></strong> Color RedUnderBg.</p>
# </html>
export RedUnderBg="\033[4;41m"

# <html><h2>Yellow</h2>
# <p><strong><code>$Yellow</code></strong> Color Yellow.</p>
# </html>
export Yellow="\033[1;33m"

# <html><h2>YellowBg</h2>
# <p><strong><code>$YellowBg</code></strong> Color YellowBg.</p>
# </html>
export YellowBg="\033[1;43m"

# <html><h2>YellowBoldItalic</h2>
# <p><strong><code>$YellowBoldItalic</code></strong> Color YellowBoldItalic.</p>
# </html>
export YellowBoldItalic="\033[3m\033[1;33m"

# <html><h2>YellowBoldItalicBg</h2>
# <p><strong><code>$YellowBoldItalicBg</code></strong> Color YellowBoldItalicBg.</p>
# </html>
export YellowBoldItalicBg="\033[3m\033[1;43m"

# <html><h2>YellowDim</h2>
# <p><strong><code>$YellowDim</code></strong> Color YellowDim.</p>
# </html>
export YellowDim="\033[2;33m"

# <html><h2>YellowDimBg</h2>
# <p><strong><code>$YellowDimBg</code></strong> Color YellowDimBg.</p>
# </html>
export YellowDimBg="\033[2;43m"

# <html><h2>YellowInvert</h2>
# <p><strong><code>$YellowInvert</code></strong> Color YellowInvert.</p>
# </html>
export YellowInvert="\033[7;33m"

# <html><h2>YellowInvertBg</h2>
# <p><strong><code>$YellowInvertBg</code></strong> Color YellowInvertBg.</p>
# </html>
export YellowInvertBg="\033[7;43m"

# <html><h2>YellowItalic</h2>
# <p><strong><code>$YellowItalic</code></strong> Color YellowItalic.</p>
# </html>
export YellowItalic="\033[3;33m"

# <html><h2>YellowItalicBg</h2>
# <p><strong><code>$YellowItalicBg</code></strong> Color YellowItalicBg.</p>
# </html>
export YellowItalicBg="\033[3;43m"

# <html><h2>YellowNormal</h2>
# <p><strong><code>$YellowNormal</code></strong> Color YellowNormal.</p>
# </html>
export YellowNormal="\033[0;33m"

# <html><h2>YellowNormalBg</h2>
# <p><strong><code>$YellowNormalBg</code></strong> Color YellowNormalBg.</p>
# </html>
export YellowNormalBg="\033[0;43m"

# <html><h2>YellowStrike</h2>
# <p><strong><code>$YellowStrike</code></strong> Color YellowStrike.</p>
# </html>
export YellowStrike="\033[9;33m"

# <html><h2>YellowStrikeBg</h2>
# <p><strong><code>$YellowStrikeBg</code></strong> Color YellowStrikeBg.</p>
# </html>
export YellowStrikeBg="\033[9;43m"

# <html><h2>YellowUnder</h2>
# <p><strong><code>$YellowUnder</code></strong> Color YellowUnder.</p>
# </html>
export YellowUnder="\033[4;33m"

# <html><h2>YellowUnderBg</h2>
# <p><strong><code>$YellowUnderBg</code></strong> Color YellowUnderBg.</p>
# </html>
export YellowUnderBg="\033[4;43m"

