# shellcheck shell=sh

#
# Symbol Colors library (generated by: color)

# <html><h2>Critical</h2>
# <p><strong><code>$Critical</code></strong> Color Critical.</p>
# </html>
export Critical="\e[7;31m✘\e[0m"

# <html><h2>Debug</h2>
# <p><strong><code>$Debug</code></strong> Color Debug.</p>
# </html>
export Debug="\e[1;35m+\e[0m"

# <html><h2>Error</h2>
# <p><strong><code>$Error</code></strong> Color Error.</p>
# </html>
export Error="\e[1;31m✘\e[0m"

# <html><h2>Finish</h2>
# <p><strong><code>$Finish</code></strong> Color Finish.</p>
# </html>
export Finish="=\e[1;32m＞\e[0m"

# <html><h2>Minus</h2>
# <p><strong><code>$Minus</code></strong> Color Minus.</p>
# </html>
export Minus="\e[1;31m+\e[0m"

# <html><h2>More</h2>
# <p><strong><code>$More</code></strong> Color More.</p>
# </html>
export More="\e[1;35m＞\e[0m"

# <html><h2>Multiply</h2>
# <p><strong><code>$Multiply</code></strong> Color Multiply.</p>
# </html>
export Multiply="\e[1;34m×\e[0m"

# <html><h2>Notice</h2>
# <p><strong><code>$Notice</code></strong> Color Notice.</p>
# </html>
export Notice="\e[1;36m‼\e[0m"

# <html><h2>Ok</h2>
# <p><strong><code>$Ok</code></strong> Color Ok.</p>
# </html>
export Ok="\e[1;32m✔\e[0m"

# <html><h2>Plus</h2>
# <p><strong><code>$Plus</code></strong> Color Plus.</p>
# </html>
export Plus="\e[1;32m+\e[0m"

# <html><h2>Start</h2>
# <p><strong><code>$Start</code></strong> Color Start.</p>
# </html>
export Start="=\e[1;34m＞\e[0m"

# <html><h2>Success</h2>
# <p><strong><code>$Success</code></strong> Color Success.</p>
# </html>
export Success="\e[1;34m◉\e[0m"

# <html><h2>Tilde</h2>
# <p><strong><code>$Tilde</code></strong> Color Tilde.</p>
# </html>
export Tilde="\e[1;34m～\e[0m"

# <html><h2>Verbose</h2>
# <p><strong><code>$Verbose</code></strong> Color Verbose.</p>
# </html>
export Verbose="\e[1;35m＋\e[0m"

# <html><h2>Wait</h2>
# <p><strong><code>$Wait</code></strong> Color Wait.</p>
# </html>
export Wait="\e[1;36m…\e[0m"

# <html><h2>Warning</h2>
# <p><strong><code>$Warning</code></strong> Color Warning.</p>
# </html>
export Warning="\e[1;33m！\e[0m"

