#!/bin/sh

# <html><h2>blackinvert</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in BlackInvert:</dt>
# <dd>
# <pre><code class="language-bash">blackinvert Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[7;30m"; printf '%b' "$*"; printf '%b' "\e[0m"
