#!/bin/sh

# <html><h2>greendim</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in GreenDim:</dt>
# <dd>
# <pre><code class="language-bash">greendim Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[2;32m"; printf '%b' "$*"; printf '%b' "\e[0m"
