#!/bin/sh

# <html><h2>grey</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in Grey:</dt>
# <dd>
# <pre><code class="language-bash">grey Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[1;37m"; printf '%b' "$*"; printf '%b' "\e[0m"
