#!/bin/sh

# <html><h2>blackbolditalic</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in BlackBoldItalic:</dt>
# <dd>
# <pre><code class="language-bash">blackbolditalic Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\e[3m\e[1;30m"; printf '%b' "$*"; printf -- '%b' "\e[0m"
