#!/bin/sh

# <html><h2>blacknormal</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in BlackNormal:</dt>
# <dd>
# <pre><code class="language-bash">blacknormal Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\e[0;30m"; printf '%b' "$*"; printf -- '%b' "\e[0m"
