#!/bin/sh

# <html><h2>blackbg - Show arguments in BlackBg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in BlackBg:</dt>
# <dd>
# <pre><code class="language-bash">blackbg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${BlackBg}"; printf '%b' "$@"; printf '%b' "${Reset}"
