#!/bin/sh

# <html><h2>blackinvert - Show arguments in BlackInvert</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in BlackInvert:</dt>
# <dd>
# <pre><code class="language-bash">blackinvert Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${BlackInvert}"; printf '%b' "$*"; printf '%b' "${Reset}"
