#!/bin/sh

# <html><h2>blacklight - Show arguments in BlackLight</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in BlackLight:</dt>
# <dd>
# <pre><code class="language-bash">blacklight Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${BlackLight}"; printf '%b' "$*"; printf '%b' "${Reset}"
