#!/bin/sh

# <html><h2>blackdim</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in BlackDim:</dt>
# <dd>
# <pre><code class="language-bash">blackdim Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\033[2;30m"; printf '%b' "$*"; printf -- '%b' "\033[0m"
