#!/bin/sh

# <html><h2>black</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in Black:</dt>
# <dd>
# <pre><code class="language-bash">black Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\033[1;30m"; printf '%b' "$*"; printf -- '%b' "\033[0m"
