#!/bin/sh

# <html><h2>blackunder - Show arguments in BlackUnder</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in BlackUnder:</dt>
# <dd>
# <pre><code class="language-bash">blackunder Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
test "$#" -eq 0 || printf '%b' "${BlackUnder}"; printf '%b' "$@"; printf '%b' "${Reset}"

