#!/bin/sh

# <html><h2>blackitalicesc</h2>
# https://mywiki.wooledge.org/BashFAQ/053
# <a href="https://mywiki.wooledge.org/BashFAQ/053">Dynamic prompt or read -p</a>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in Escaped BlackItalic for $PS1 ,dynamic prompt or read -p:</dt>
# <dd>
# <pre><code class="language-bash">blackitalicesc Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%s' "\[\033[3;30m\]" "$*" "\[\033[0m\]"
