#!/bin/sh

# <html><h2>blackbolditalicbg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in BlackBoldItalicBg:</dt>
# <dd>
# <pre><code class="language-bash">blackbolditalicbg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[3m\e[1;40m"; printf '%b' "$*"; printf '%b' "\e[0m"
