#!/bin/sh

# <html><h2>blackbold - Show arguments in BlackBold</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in BlackBold:</dt>
# <dd>
# <pre><code class="language-bash">blackbold Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
test "$#" -eq 0 || printf '%b' "${BlackBold}"; printf '%b' "$@"; printf '%b' "${Reset}"

