#!/bin/sh

# <html><h2>bluedim - Show arguments in BlueDim</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in BlueDim:</dt>
# <dd>
# <pre><code class="language-bash">bluedim Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${BlueDim}"; printf '%b' "$@"; printf '%b' "${Reset}"
