#!/bin/sh

# <html><h2>bluebold - Show arguments in BlueBold</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in BlueBold:</dt>
# <dd>
# <pre><code class="language-bash">bluebold Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${BlueBold}"; printf '%b' "$@"; printf '%b' "${Reset}"
