#!/bin/sh

# <html><h2>blue</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in Blue:</dt>
# <dd>
# <pre><code class="language-bash">blue Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\e[1;34m"; printf '%b' "$*"; printf -- '%b' "\e[0m"
