#!/bin/sh

# <html><h2>bluestrike</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in BlueStrike:</dt>
# <dd>
# <pre><code class="language-bash">bluestrike Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[9;34m"; printf '%b' "$*"; printf '%b' "\e[0m"
