#!/bin/sh

# <html><h2>bluestrikebg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in BlueStrikeBg:</dt>
# <dd>
# <pre><code class="language-bash">bluestrikebg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[9;44m"; printf '%b' "$*"; printf '%b' "\e[0m"
