#!/bin/sh

# <html><h2>bluebg - Show arguments in BlueBg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in BlueBg:</dt>
# <dd>
# <pre><code class="language-bash">bluebg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${BlueBg}"; printf '%b' "$@"; printf '%b' "${Reset}"

