#!/bin/sh

# <html><h2>blueinvert</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in BlueInvert:</dt>
# <dd>
# <pre><code class="language-bash">blueinvert Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\e[7;34m"; printf '%b' "$*"; printf -- '%b' "\e[0m"
