#!/bin/sh

# <html><h2>bluebolditalic</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in BlueBoldItalic:</dt>
# <dd>
# <pre><code class="language-bash">bluebolditalic Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\e[3m\e[1;34m"; printf '%b' "$*"; printf -- '%b' "\e[0m"
