#!/bin/sh

# <html><h2>blueinvertbg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in BlueInvertBg:</dt>
# <dd>
# <pre><code class="language-bash">blueinvertbg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\e[7;44m"; printf '%b' "$*"; printf -- '%b' "\e[0m"
