#!/bin/sh

# <html><h2>blueunder - Show arguments in BlueUnder</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in BlueUnder:</dt>
# <dd>
# <pre><code class="language-bash">blueunder Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${BlueUnder}"; printf '%b' "$@"; printf '%b' "${Reset}"
