#!/bin/sh

# <html><h2>boldesc</h2>
# https://mywiki.wooledge.org/BashFAQ/053
# <a href="https://mywiki.wooledge.org/BashFAQ/053">Dynamic prompt or read -p</a>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in BoldEsc escaped for $PS1,dynamic prompt or read -p:</dt>
# <dd>
# <pre><code class="language-bash">boldesc Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%s' "\[\e[1m\]" "$*" "\[\e[0m\]"
