#!/bin/sh

# <html><h2>bold</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in Bold:</dt>
# <dd>
# <pre><code class="language-bash">bold Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\033[1m"; printf '%b' "$*"; printf -- '%b' "\033[0m"
