#!/bin/sh

# <html><h2>[7;31m✘[0m</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show arguments separated with space, prefixed with Critical symbol.
# All arguments in Red:
# </dt>
# <dd>
# <pre><code class="language-bash">Critical Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
if [ "${QUIET-0}" -ne 1 ]; then
  first="$(red "$@")"
  printf '%s' "[7;31m✘[0m" "${first:+ "${first}"}"
  [ ! "${first-}" ] || echo
fi
