#!/bin/sh

# <html><h2>--</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show arguments separated with space, prefixed with Critical symbol.
# All arguments in Red:
# </dt>
# <dd>
# <pre><code class="language-bash">Critical Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
rc=$?
[ "${QUIET-0}" -ne 1 ] || exit $rc

msg="$(red "$@")"
printf -- '%s' "--" "${msg:+ "${msg}"}"
[ ! "${msg-}" ] || echo
exit $rc
