#!/bin/sh

# <html><h2>cyanitalicesc</h2>
# https://mywiki.wooledge.org/BashFAQ/053
# <a href="https://mywiki.wooledge.org/BashFAQ/053">Dynamic prompt or read -p</a>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in Escaped CyanItalic for $PS1 ,dynamic prompt or read -p:</dt>
# <dd>
# <pre><code class="language-bash">cyanitalicesc Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%s' "\[\e[3;36m\]" "$*" "\[\e[0m\]"
