#!/bin/sh

# <html><h2>cyanbolditalicbg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in CyanBoldItalicBg:</dt>
# <dd>
# <pre><code class="language-bash">cyanbolditalicbg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[3m\e[1;46m"; printf '%b' "$*"; printf '%b' "\e[0m"
