#!/bin/sh

# <html><h2>cyan - Show arguments in Cyan</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in Cyan:</dt>
# <dd>
# <pre><code class="language-bash">cyan Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${Cyan}"; printf '%b' "$@"; printf '%b' "${Reset}"

