#!/bin/sh

# <html><h2>cyanunder - Show arguments in CyanUnder</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in CyanUnder:</dt>
# <dd>
# <pre><code class="language-bash">cyanunder Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${CyanUnder}"; printf '%b' "$*"; printf '%b' "${Reset}"
