#!/bin/sh

# <html><h2>cyanstrikebg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in CyanStrikeBg:</dt>
# <dd>
# <pre><code class="language-bash">cyanstrikebg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\e[9;46m"; printf '%b' "$*"; printf -- '%b' "\e[0m"
