#!/bin/sh

# <html><h2>cyanunder</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in CyanUnder:</dt>
# <dd>
# <pre><code class="language-bash">cyanunder Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[4;36m"; printf '%b' "$*"; printf '%b' "\e[0m"
