#!/bin/sh

# <html><h2>cyaninvert - Show arguments in CyanInvert</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in CyanInvert:</dt>
# <dd>
# <pre><code class="language-bash">cyaninvert Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${CyanInvert}"; printf '%b' "$@"; printf '%b' "${Reset}"
