#!/bin/sh

# <html><h2>cyandim - Show arguments in CyanDim</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in CyanDim:</dt>
# <dd>
# <pre><code class="language-bash">cyandim Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${CyanDim}"; printf '%b' "$@"; printf '%b' "${Reset}"
