#!/bin/sh

# <html><h2>[1;35m+[0m</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show arguments separated with space, prefixed with Debug symbol. First argument in Normal,
# other Italic:
# </dt>
# <dd>
# <pre><code class="language-bash">Debug Show Text
# </code></pre>
# </dd>
# </dl>
# </html>

if [ "${QUIET-0}" -ne 1 ]; then
  first="$(FirstOther "$@")"
  printf '%s' "[1;35m+[0m" "${first:+ "${first}"}"
  [ ! "${first-}" ] || echo
fi
