#!/bin/sh

# <html><h2>[1;35m＋[0m</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show arguments separated with space, prefixed with Debug symbol.
# All arguments in MagentaDim:
# </dt>
# <dd>
# <pre><code class="language-bash">Debug Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
rc=$?
[ "${QUIET-0}" -ne 1 ] || exit $rc

msg="$(magentadim "$@")"
printf '%s' "[1;35m＋[0m" "${msg:+ "${msg}"}"
[ ! "${msg-}" ] || echo
exit $rc
