#!/bin/sh

# <html><h2>[1;31m✘[0m</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show arguments separated with space, prefixed with Error symbol.
# First argument in Bold, other Italic:
# </dt>
# <dd>
# <pre><code class="language-bash">Error Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
if [ "${QUIET-0}" -ne 1 ]; then
  first="$(firstother "$@")"
  printf '%s' "[1;31m✘[0m" "${first:+ "${first}"}"
  [ ! "${first-}" ] || echo
fi
