#!/bin/sh

# <html><h2>--</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show arguments separated with space, prefixed with Error symbol.
# First argument in Bold, other Italic:
# </dt>
# <dd>
# <pre><code class="language-bash">Error Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
rc=$?
[ "${QUIET-0}" -ne 1 ] || exit $rc

msg="$(firstother "$@")"
printf -- '%s' "--" "${msg:+ "${msg}"}"
[ ! "${msg-}" ] || echo
exit $rc
