#!/bin/sh

# <html><h2>firstitalic</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# First in Italic and rest normal:
# </dt>
# <dd>
# <pre><code class="language-bash">firstItalic Show Text
# </code></pre>
# </dd>
# </dl>
# </html>

[ $# -ne 0 ] || exit
[ "$1" != "space" ] || { space=" "; shift; }
italic "${space-}$1"
[ $# -ne 0 ] || exit
shift
printf '%s\n' " $*"
