#!/bin/sh

# <html><h2>greenbolditalicbg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in GreenBoldItalicBg:</dt>
# <dd>
# <pre><code class="language-bash">greenbolditalicbg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[3m\e[1;42m"; printf '%b' "$*"; printf '%b' "\e[0m"
