#!/bin/sh

# <html><h2>greenbold - Show arguments in GreenBold</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in GreenBold:</dt>
# <dd>
# <pre><code class="language-bash">greenbold Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${GreenBold}"; printf '%b' "$@"; printf '%b' "${Reset}"
