#!/bin/sh

# <html><h2>greendimbg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in GreenDimBg:</dt>
# <dd>
# <pre><code class="language-bash">greendimbg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\e[2;42m"; printf '%b' "$*"; printf -- '%b' "\e[0m"
