#!/bin/sh

# <html><h2>greeninvert - Show arguments in GreenInvert</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in GreenInvert:</dt>
# <dd>
# <pre><code class="language-bash">greeninvert Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${GreenInvert}"; printf '%b' "$@"; printf '%b' "${Reset}"

