#!/bin/sh

# <html><h2>green - Show arguments in Green</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in Green:</dt>
# <dd>
# <pre><code class="language-bash">green Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
test "$#" -eq 0 || printf '%b' "${Green}"; printf '%b' "$@"; printf '%b' "${Reset}"

