#!/bin/sh

# <html><h2>greenbg - Show arguments in GreenBg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in GreenBg:</dt>
# <dd>
# <pre><code class="language-bash">greenbg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${GreenBg}"; printf '%b' "$*"; printf '%b' "${Reset}"
