#!/bin/sh

# <html><h2>greenstrikebg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in GreenStrikeBg:</dt>
# <dd>
# <pre><code class="language-bash">greenstrikebg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[9;42m"; printf '%b' "$*"; printf '%b' "\e[0m"
