#!/bin/sh

# <html><h2>greenitalicesc</h2>
# https://mywiki.wooledge.org/BashFAQ/053
# <a href="https://mywiki.wooledge.org/BashFAQ/053">Dynamic prompt or read -p</a>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in GreenItalicEsc escaped for $PS1,dynamic prompt or read -p:</dt>
# <dd>
# <pre><code class="language-bash">greenitalicesc Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '\001%s\002%s\001%s\002' "\[\e[3;32m\]" "$*" "\[\e[0m\]"
