#!/bin/sh

# <html><h2>greenstrike</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in GreenStrike:</dt>
# <dd>
# <pre><code class="language-bash">greenstrike Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\e[9;32m"; printf '%b' "$*"; printf -- '%b' "\e[0m"
