#!/bin/sh

# <html><h2>greenlight - Show arguments in GreenLight</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in GreenLight:</dt>
# <dd>
# <pre><code class="language-bash">greenlight Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${GreenLight}"; printf '%b' "$*"; printf '%b' "${Reset}"
