#!/bin/sh

# <html><h2>greyunder - Show arguments in GreyUnder</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in GreyUnder:</dt>
# <dd>
# <pre><code class="language-bash">greyunder Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${GreyUnder}"; printf '%b' "$@"; printf '%b' "${Reset}"

