#!/bin/sh

# <html><h2>greystrikebg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in GreyStrikeBg:</dt>
# <dd>
# <pre><code class="language-bash">greystrikebg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[9;47m"; printf '%b' "$*"; printf '%b' "\e[0m"
