#!/bin/sh

# <html><h2>greybg - Show arguments in GreyBg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in GreyBg:</dt>
# <dd>
# <pre><code class="language-bash">greybg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${GreyBg}"; printf '%b' "$@"; printf '%b' "${Reset}"
