#!/bin/sh

# <html><h2>grey - Show arguments in Grey</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in Grey:</dt>
# <dd>
# <pre><code class="language-bash">grey Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${Grey}"; printf '%b' "$*"; printf '%b' "${Reset}"
