#!/bin/sh

# <html><h2>greylight - Show arguments in GreyLight</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in GreyLight:</dt>
# <dd>
# <pre><code class="language-bash">greylight Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${GreyLight}"; printf '%b' "$*"; printf '%b' "${Reset}"
