#!/bin/sh

# <html><h2>greydim - Show arguments in GreyDim</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in GreyDim:</dt>
# <dd>
# <pre><code class="language-bash">greydim Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${GreyDim}"; printf '%b' "$@"; printf '%b' "${Reset}"

