#!/bin/sh

# <html><h2>greynormal</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in GreyNormal:</dt>
# <dd>
# <pre><code class="language-bash">greynormal Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[0;37m"; printf '%b' "$*"; printf '%b' "\e[0m"
