#!/bin/sh

# <html><h2>Installing</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show first argument in Italic and second Installing, prefixed with Start symbol:
# </dt>
# <dd>
# <pre><code class="language-bash">Installing Brew
# </code></pre>
# </dd>
# </dl>
# </html>
ret=$?
Start "${1}:" "Installing"
exit $ret
