#!/bin/sh

# <html><h2>invert</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in Invert:</dt>
# <dd>
# <pre><code class="language-bash">invert Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[[7m"; printf '%b' "$*"; printf '%b' "\e[0m"
