#!/bin/sh

# <html><h2>magenta - Show arguments in Magenta</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in Magenta:</dt>
# <dd>
# <pre><code class="language-bash">magenta Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${Magenta}"; printf '%b' "$@"; printf '%b' "${Reset}"

