#!/bin/sh

# <html><h2>magentadim</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in MagentaDim:</dt>
# <dd>
# <pre><code class="language-bash">magentadim Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\e[2;35m"; printf '%b' "$*"; printf -- '%b' "\e[0m"
