#!/bin/sh

# <html><h2>magentadim - Show arguments in MagentaDim</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in MagentaDim:</dt>
# <dd>
# <pre><code class="language-bash">magentadim Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
test "$#" -eq 0 || printf '%b' "${MagentaDim}"; printf '%b' "$@"; printf '%b' "${Reset}"

