#!/bin/sh

# <html><h2>magentaunder - Show arguments in MagentaUnder</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in MagentaUnder:</dt>
# <dd>
# <pre><code class="language-bash">magentaunder Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${MagentaUnder}"; printf '%b' "$*"; printf '%b' "${Reset}"
