#!/bin/sh

# <html><h2>magentabold - Show arguments in MagentaBold</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in MagentaBold:</dt>
# <dd>
# <pre><code class="language-bash">magentabold Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${MagentaBold}"; printf '%b' "$*"; printf '%b' "${Reset}"
