#!/bin/sh

# <html><h2>magentabolditalicbg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in MagentaBoldItalicBg:</dt>
# <dd>
# <pre><code class="language-bash">magentabolditalicbg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\e[3m\e[1;45m"; printf '%b' "$*"; printf -- '%b' "\e[0m"
