#!/bin/sh

# <html><h2>magentaitalicbg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in MagentaItalicBg:</dt>
# <dd>
# <pre><code class="language-bash">magentaitalicbg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\033[3;45m"; printf '%b' "$*"; printf -- '%b' "\033[0m"
