#!/bin/sh

# <html><h2>magentanormal</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in MagentaNormal:</dt>
# <dd>
# <pre><code class="language-bash">magentanormal Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\033[0;35m"; printf '%b' "$*"; printf -- '%b' "\033[0m"
