#!/bin/sh

# <html><h2>Notice</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show arguments separated with space, prefixed with Notice symbol. If more than one arguments then first in Italic:
# </dt>
# <dd>
# <pre><code class="language-bash">Notice Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
ret=$?

if { [ "${QUIET-0}" -ne 1 ] && [ "${QQUIET-0}" -ne 1 ]; }; then
  printf '%b' "\e[1;36m‼\e[0m"
  [ $# -ne 0 ] || exit $ret
  [ $# -eq 1 ] || { italic " $1"; shift; }
  printf '%s\n' " $*"
fi

exit $ret
