#!/bin/sh

# <html><h2>[1;36m‼[0m</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show arguments separated with space, prefixed with Notice symbol. First argument in Italic, other Normal:
# </dt>
# <dd>
# <pre><code class="language-bash">Notice Show Text
# </code></pre>
# </dd>
# </dl>
# </html>

if { [ "${QUIET-0}" -ne 1 ] && [ "${QQUIET-0}" -ne 1 ]; }; then
  first="$(FirstArg "$@")"
  printf '%s' "[1;36m‼[0m" "${first:+ "${first}\n"}"
fi
