#!/bin/sh
# <html><h2>[1;32m✔[0m</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show arguments separated with space, prefixed with Ok symbol.
# All arguments in Green:
# </dt>
# <dd>
# <pre><code class="language-bash">Ok Show Text
# </code></pre>
# </dd>
# </dl>
# </html>

if [ "${QUIET-0}" -ne 1 ]; then
  first="$(green "$@")"
  printf '%s' "[1;32m✔[0m" "${first:+ "${first}"}"
  [ ! "${first-}" ] || echo
fi
