#!/bin/sh

# <html><h2>Plus</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show arguments separated with space and prefixed with Plus. If more than one arguments then first in Italic:
# </dt>
# <dd>
# <pre><code class="language-bash">Plus Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
ret=$?

if { [ "${QUIET-0}" -ne 1 ] && [ "${QQUIET-0}" -ne 1 ];}; then
  printf '%b' "\e[1;32m+\e[0m"
  [ $# -ne 0 ] || exit $ret
  [ $# -eq 1 ] || italic "$1 "
  printf '%s\n' "$*"
fi

exit $ret
