#!/bin/sh

# <html><h2>red</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in Red:</dt>
# <dd>
# <pre><code class="language-bash">red Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\e[1;31m"; printf '%b' "$*"; printf -- '%b' "\e[0m"
