#!/bin/sh

# <html><h2>redbold - Show arguments in RedBold</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in RedBold:</dt>
# <dd>
# <pre><code class="language-bash">redbold Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${RedBold}"; printf '%b' "$*"; printf '%b' "${Reset}"
