#!/bin/sh

# <html><h2>redbg - Show arguments in RedBg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in RedBg:</dt>
# <dd>
# <pre><code class="language-bash">redbg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${RedBg}"; printf '%b' "$*"; printf '%b' "${Reset}"
