#!/bin/sh

# <html><h2>reddim - Show arguments in RedDim</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in RedDim:</dt>
# <dd>
# <pre><code class="language-bash">reddim Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${RedDim}"; printf '%b' "$@"; printf '%b' "${Reset}"

