#!/bin/sh

# <html><h2>redlight - Show arguments in RedLight</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in RedLight:</dt>
# <dd>
# <pre><code class="language-bash">redlight Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${RedLight}"; printf '%b' "$*"; printf '%b' "${Reset}"
