#!/bin/sh

# <html><h2>redstrike</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in RedStrike:</dt>
# <dd>
# <pre><code class="language-bash">redstrike Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\e[9;31m"; printf '%b' "$*"; printf -- '%b' "\e[0m"
