#!/bin/sh

# <html><h2>redunder - Show arguments in RedUnder</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in RedUnder:</dt>
# <dd>
# <pre><code class="language-bash">redunder Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
test "$#" -eq 0 || printf '%b' "${RedUnder}"; printf '%b' "$@"; printf '%b' "${Reset}"

