#!/bin/sh

# <html><h2>reset - Show arguments in Reset</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in Reset:</dt>
# <dd>
# <pre><code class="language-bash">reset Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${Reset}"; printf '%b' "$@"; printf '%b' "${Reset}"
