#!/bin/sh
# <html><h2>[1;34m◉[0m</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show arguments separated with space, prefixed with Success symbol.
# All arguments in Blue:
# </dt>
# <dd>
# <pre><code class="language-bash">Success Show Text
# </code></pre>
# </dd>
# </dl>
# </html>

if [ "${QUIET-0}" -ne 1 ]; then
  first="$(blue "$@")"
  printf '%s' "[1;34m◉[0m" "${first:+ "${first}"}"
  [ ! "${first-}" ] || echo
fi
