#!/bin/sh

# <html><h2>Tilde</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show arguments separated with space, prefixed with Tilde symbol. If more than one arguments then first in Italic:
# </dt>
# <dd>
# <pre><code class="language-bash">Tilde Show Text
# </code></pre>
# </dd>
# </dl>
# </html>

if { [ "${QUIET-0}" -ne 1 ] && [ "${QQUIET-0}" -ne 1 ]; }; then
  printf '%b' "\e[1;34m～\e[0m"
  firstItalic space "$@"
fi
