#!/bin/sh

# <html><h2>--</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show arguments separated with space, prefixed with Tilde symbol.
# All arguments in Blue:
# </dt>
# <dd>
# <pre><code class="language-bash">Tilde Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
rc=$?
[ "${QUIET-0}" -ne 1 ] || exit $rc

msg="$(blue "$@")"
printf '%s' "--" "${msg:+ "${msg}"}"
[ ! "${msg-}" ] || echo
exit $rc
