#!/bin/sh

# <html><h2>[1;35m＋[0m</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show arguments separated with space, prefixed with Verbose symbol.
# All arguments in MagentaDim:
# </dt>
# <dd>
# <pre><code class="language-bash">Verbose Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
if [ "${QUIET-0}" -ne 1 ] && { [ "${VERBOSE-0}" -eq 1 ] || [ "${DRY_RUN-0}" -eq 1 ]; }; then
  first="$(magentadim "$@")"
  printf '%s' "[1;35m＋[0m" "${first:+ "${first}"}"
  [ ! "${first-}" ] || echo
fi
