#!/bin/sh
# <html><h2>Dry Run</h2>
# <p><strong><code>$DRY_RUN</code></strong> (Default: 0).</p>
# <p>Activate with either of:</p>
# <ul>
# <li><code>DRY_RUN=1</code></li>
# <li><code>--dryrun</code></li>
# </ul>
# </html>
DRY_RUN="${DRY_RUN:-0}"

# <html><h2>Show Verbose Messages</h2>
# <p><strong><code>$VERBOSE</code></strong> (Default: 0).</p>
# <p><strong><code>Verbose messages are shown if set to 1.</code></strong></p>
# <p>Activate with either of:</p>
# <ul>
# <li><code>VERBOSE=1</code></li>
# <li><code>--verbose</code></li>
# </ul>
# </html>
VERBOSE="${VERBOSE:-0}"
# <html><h2>[1;35m＋[0m</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show arguments separated with space, prefixed with Verbose symbol. First argument in Bold,
# other Italic:
# </dt>
# <dd>
# <pre><code class="language-bash">Verbose Show Text
# </code></pre>
# </dd>
# </dl>
# </html>

if [ "${QUIET-0}" -ne 1 ] && { [ "${VERBOSE}" -eq 1 ] || [ "${DRY_RUN-}" -eq 1 ]; }; then
  first="$(FirstOther "\e[1;35m$@\e[0m")"
  printf '%s' "[1;35m＋[0m" "${first:+ "${first}"}"
  [ ! "${first-}" ] || echo
fi
