#!/bin/sh

# <html><h2>--</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show arguments separated with space, prefixed with Verbose symbol.
# All arguments in CyanDim:
# </dt>
# <dd>
# <pre><code class="language-bash">Verbose Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
rc=$?
[ "${QUIET-0}" -ne 1 ] || exit $rc
[ "${VERBOSE-0}" -eq 1 ] || exit $rc
msg="$(cyandim "$@")"
printf '%s' "--" "${msg:+ "${msg}"}"
[ ! "${msg-}" ] || echo
exit $rc
