#!/bin/sh

# <html><h2>[1;33m![0m</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show arguments separated with space, prefixed with Warning symbol. First argument in Italic, other Normal:
# </dt>
# <dd>
# <pre><code class="language-bash">Warning Show Text
# </code></pre>
# </dd>
# </dl>
# </html>

if [ "${QUIET-0}" -ne 1 ]; then
  first="$(FirstArg "$@")"
  printf '%s' "[1;33m![0m" "${first:+ "${first}"}"
  [ ! "${first-}" ] || echo
fi
