#!/bin/sh

# <html><h2>yellowbg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in YellowBg:</dt>
# <dd>
# <pre><code class="language-bash">yellowbg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\033[1;43m"; printf '%b' "$*"; printf -- '%b' "\033[0m"
