#!/bin/sh

# <html><h2>yellowunder - Show arguments in YellowUnder</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in YellowUnder:</dt>
# <dd>
# <pre><code class="language-bash">yellowunder Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${YellowUnder}"; printf '%b' "$@"; printf '%b' "${Reset}"
