#!/bin/sh

# <html><h2>yellowdim - Show arguments in YellowDim</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in YellowDim:</dt>
# <dd>
# <pre><code class="language-bash">yellowdim Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "${YellowDim}"; printf '%b' "$@"; printf '%b' "${Reset}"

