#!/bin/sh

# <html><h2>yellowstrike</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in YellowStrike:</dt>
# <dd>
# <pre><code class="language-bash">yellowstrike Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[9;33m"; printf '%b' "$*"; printf '%b' "\e[0m"
