#!/bin/sh

# <html><h2>yellowitalicesc</h2>
# https://mywiki.wooledge.org/BashFAQ/053
# <a href="https://mywiki.wooledge.org/BashFAQ/053">Dynamic prompt or read -p</a>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments in YellowItalicEsc escaped for $PS1,dynamic prompt or read -p:</dt>
# <dd>
# <pre><code class="language-bash">yellowitalicesc Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
#[ $# -eq 0 ] || printf -- '\001%s\002%s\001%s\002' "\[\e[3;33m\]" "$*" "\[\e[0m\]"
[ $# -eq 0 ] || printf -- '%s' "\[\e[3;33m\]" "$*" "\[\e[0m\]"
