#!/bin/sh

# <html><h2>yellowbolditalic</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in YellowBoldItalic:</dt>
# <dd>
# <pre><code class="language-bash">yellowbolditalic Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\e[3m\e[1;33m"; printf '%b' "$*"; printf -- '%b' "\e[0m"
