#!/bin/sh

# <html><h2>yellowunderbg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in YellowUnderBg:</dt>
# <dd>
# <pre><code class="language-bash">yellowunderbg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[4;43m"; printf '%b' "$*"; printf '%b' "\e[0m"
