name: tap

on:
  push:
    tags:
      - '**'

jobs:
  tap:
    runs-on: ubuntu-latest
    name: tap
    steps:
      - name: "Release to Homebrew tap"
        uses: j5pu/actions/tap@main
        with:
          github_token: ${{ secrets.TOKEN }}
          depends_on: |
            "bats-core"
            "bats-core/bats-core/bats-assert"
            "bats-core/bats-core/bats-file"
            "bats-core/bats-core/bats-support"
          install: 'bin.install "bats.bash"'
          test: |
            system sh, -c, "#{HOMEBREW_PREFIX}/bin/bats.bash && command -v assert_file_exist"
