#!/bin/sh

# <html><h2>bluedim</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in BlueDim:</dt>
# <dd>
# <pre><code class="language-bash">bluedim Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[2;34m"; printf '%b' "$*"; printf '%b' "\e[0m"
