#!/bin/sh

# <html><h2>cyandimbg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in CyanDimBg:</dt>
# <dd>
# <pre><code class="language-bash">cyandimbg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[2;46m"; printf '%b' "$*"; printf '%b' "\e[0m"
