#!/bin/sh

# <html><h2>redinvert</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in RedInvert:</dt>
# <dd>
# <pre><code class="language-bash">redinvert Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[7;31m"; printf '%b' "$*"; printf '%b' "\e[0m"
