#!/bin/sh

# <html><h2>reset</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in Reset:</dt>
# <dd>
# <pre><code class="language-bash">reset Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[0m"; printf '%b' "$*"; printf '%b' "\e[0m"
