#!/bin/sh

# <html><h2>cyanstrike</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in CyanStrike:</dt>
# <dd>
# <pre><code class="language-bash">cyanstrike Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf -- '%b' "\e[9;36m"; printf '%b' "$*"; printf -- '%b' "\e[0m"
