#!/bin/sh

# <html><h2>[1;33m！‼[0m</h2>
# <h3>Examples</h3>
# <dl>
# <dt>
# Show arguments separated with space, prefixed with Notice symbol.
# All arguments in YellowDim:
# </dt>
# <dd>
# <pre><code class="language-bash">Notice Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
rc=$?
[ "${QUIET-0}" -ne 1 ] || exit $rc

msg="$(yellowdim "$@")"
printf -- '%s' "[1;33m！‼[0m" "${msg:+ "${msg}"}"
[ ! "${msg-}" ] || echo
exit $rc
