#!/bin/sh

# <html><h2>bluebg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in BlueBg:</dt>
# <dd>
# <pre><code class="language-bash">bluebg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[1;44m"; printf '%b' "$*"; printf '%b' "\e[0m"
