#!/bin/sh

# <html><h2>magentainvertbg</h2>
# <h3>Examples</h3>
# <dl>
# <dt>Show arguments with space in MagentaInvertBg:</dt>
# <dd>
# <pre><code class="language-bash">magentainvertbg Show Text
# </code></pre>
# </dd>
# </dl>
# </html>
[ $# -eq 0 ] || printf '%b' "\e[7;45m"; printf '%b' "$*"; printf '%b' "\e[0m"
